name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"       # jalan tiap hari jam 00:00 UTC (bisa diubah)
  workflow_dispatch:          # bisa dijalankan manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Virgi6ix
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
